// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


// await Firebase.initializeApp(
// options: DefaultFirebaseOptions.currentPlatform,
// );
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuLryh3THAOcOS8LIN04u6hfx_y1KBy0s',
    appId: '1:587137851621:web:3acfb28a0cfcf1e7c1b40c',
    messagingSenderId: '587137851621',
    projectId: 'business-card-app-a464f',
    authDomain: 'business-card-app-a464f.firebaseapp.com',
    storageBucket: 'business-card-app-a464f.firebasestorage.app',
    measurementId: 'G-5CFGZT8G26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOumn_Nnxhkzk5OItCfpHvJ1wKYrwaTL4',
    appId: '1:587137851621:android:af0074e100358260c1b40c',
    messagingSenderId: '587137851621',
    projectId: 'business-card-app-a464f',
    storageBucket: 'business-card-app-a464f.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFEDs4YAX6vt0vgqdKBk2QKFackbSNmtI',
    appId: '1:587137851621:ios:c0c720a9278f99c2c1b40c',
    messagingSenderId: '587137851621',
    projectId: 'business-card-app-a464f',
    storageBucket: 'business-card-app-a464f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuLryh3THAOcOS8LIN04u6hfx_y1KBy0s',
    appId: '1:587137851621:web:d55197e93a45ab68c1b40c',
    messagingSenderId: '587137851621',
    projectId: 'business-card-app-a464f',
    authDomain: 'business-card-app-a464f.firebaseapp.com',
    storageBucket: 'business-card-app-a464f.firebasestorage.app',
    measurementId: 'G-Y13MDTYJ7W',
  );
}
